model:
  target: model.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 1024
    feature_size: 24
    timesteps: 1024
    sampling_timesteps: 1024
    loss_type: 'l1'
    beta_schedule: 'linear'
    label_dim: 35

  backbone:
    target: model.transformer.Transformer
    params:
      n_layer_enc: 2
      n_layer_dec: 8
      d_model: 32
      n_head : 4
      mlp_hidden_times: 4
      attn_pdrop: 0.1
      resit_pdrop: 0.1
      kernel_size: 5
      padding_size: 2
      use_mamba: True
        
    mamba:
      d_inner: 32
      dt_rank: 4
      d_conv: 5
      d_state: 16
      linear_bias: False
      conv_bias: True

solver:
  base_lr: 1.0e-5
  max_epochs: 10000
  results_folder: ./Checkpoints_mamba
  gradient_accumulate_every: 2
  save_cycle: 1000  # max_epochs // 10
  ema:
    decay: 0.99
    update_interval: 10
  
  scheduler:
    target: lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 200
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 100 
      verbose: False

dataset:
  batch_size: 16
  samples:
    num_sample: 4000
    size_every: 100